sudo: false
language: python

cache: pip

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install psycopg2==2.6.1
  - travis_retry pip install celery==4.0.0
  - travis_retry pip install dj-database-url==0.4.1
  - travis_retry pip install futures     # For python 2.7

services:
  - postgresql

script:
  - python manage.py test
