sudo: false
language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.5"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="Django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO="Django>=1.4,<1.5"

    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"

    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install psycopg2==2.6.1
  - travis_retry pip install django-celery==3.1.17
  - travis_retry pip install futures     # For python 2.7

services:
  - postgresql

before_script:
  - createdb test

script:
  - python runtests.py
